clc; clear; close all;
set(groot,'defaultFigureRenderer','opengl');

FT_file = 'E:\University\My Thesis\Flac model\New\Maku_PT2_Data\Data\FAILURE_TIMES_v6.mat';
outDir  = 'E:\University\My Thesis\Flac model\New\Maku_PT2_Data\Failure plots';

if ~exist(outDir,'dir'), mkdir(outDir); end

ResponseLabels = final_response_labels();

plot_grid_median_failure_time_7x10_updated(FT_file, ...
    'FailureMode','response', ...
    'TimeUnit','s', ...
    'Points',1:10, ...
    'Responses',1:7, ...
    'ResponseLabels',ResponseLabels, ...
    'ShowValues',true, ...
    'ValueFormat','%.2f', ...
    'ShowFailedPct',true, ...
    'PctFormat','%.0f%%', ...
    'TextMode','both', ...
    'Colormap','hot', ...
    'RobustLimits',true, ...
    'CLimPctl',[5 95], ...
    'SaveDir',outDir, ...
    'FileTag','', ...
    'ExportDPI',300, ...
    'FigPosition',[60 60 4200 2800], ...
    'FontName','Arial', ...
    'FontSize',26, ...
    'CellFontSize',12, ...
    'TopLabelFontSize',26, ...
    'SideLabelFontSize',26, ...
    'AxesPosition',[0.060 0.055 0.82 0.89]);

disp('DONE: Median detected-transition-time heatmap saved.');
