% ========================================================================
% CALLER: BUILD METRICS FROM SCRATCH, THEN PLOT
% ========================================================================
clc; clear; close all;
set(groot,'defaultFigureRenderer','opengl');

baseRoot = 'E:\University\My Thesis\Flac model\New\Maku_PT2_Data';

Models   = {'ELM','ELM-IGWO','ELM-ACOR','ELM-ABC'};
Baseline = 'ELM';

ResponseLabels = final_response_labels();

ResponseMarkers = {'o','s','^','d','p','h','*'};

FolderByModel = containers.Map();
FolderByModel('ELM')      = 'ELM';
FolderByModel('ELM-IGWO') = 'ELMIGWO';
FolderByModel('ELM-ACOR') = 'ELMACOR';
FolderByModel('ELM-ABC')  = 'ELMABC';

RootByModel = struct();
for i = 1:numel(Models)
    m = Models{i};
    folderTok = FolderByModel(m);
    rootDir = fullfile(baseRoot, [folderTok '_FULL70_OUT']);
    if ~exist(rootDir,'dir')
        error('Model output root not found:\n%s', rootDir);
    end
    RootByModel.(matlab.lang.makeValidName(m)) = rootDir;
end

plot_compare_models_metrics_updated( ...
    'OutRoot',     baseRoot, ...
    'SaveDir',     baseRoot, ...
    'RootByModel', RootByModel, ...
    'Models',      Models, ...
    'Metrics',     {'R2','RMSE','MAE','a10'}, ...
    'Baseline',    Baseline, ...
    'Points',      1:10, ...
    'Responses',   1:7, ...
    'ResponseLabels',  ResponseLabels, ...
    'ResponseMarkers', ResponseMarkers, ...
    'DotBy',       'response', ...
    'ErrorScale',  'normalized', ...
    'NormScope',   'per_response', ...
    'NormMethod',  'p95p5', ...
    'NormRefModel','ELM', ...
    'MinSafe',     50, ...
    'LogFloor',    1e-10, ...
    'RatioFloor',  1e-10, ...
    'DeltaClip',   6, ...
    'MarkerSize',  42, ...
    'MarkerLineWidth', 0.6, ...
    'ShowLegend',  true, ...
    'DashboardLegendGap', true, ...
    'DeltaLegendGap',     true, ...
    'DashboardLegendPosition', [0.395 0.905 0.21 0.055], ...
    'DeltaLegendPosition',     [0.395 0.905 0.21 0.055], ...
    'WinsLegendLocation',      'south', ...
    'Padding',     'compact', ...
    'TileSpacing', 'compact', ...
    'FigPosition', [60 60 4200 2800], ...
    'ExportDPI',   300, ...
    'WriteExcel',  true);

disp('DONE');
