clc; clear; close all;
set(groot,'defaultFigureRenderer','opengl');

FT_file   = 'E:\University\My Thesis\Flac model\New\Maku_PT2_Data\Data\FAILURE_TIMES_v6.mat';
FULL_file = 'E:\University\My Thesis\Flac model\New\Maku_PT2_Data\Data\FULL_ALL_POINTS_ALL_RESPONSES_XY.mat';
outDir    = 'E:\University\My Thesis\Flac model\New\Maku_PT2_Data\Failure plots';

if ~exist(outDir,'dir'), mkdir(outDir); end

ResponseLabels = final_response_labels();

plot_grid_failure_summary_7x10_updated(FT_file, FULL_file, ...
    'FailureMode','response', ...
    'Points',1:10, ...
    'Responses',1:7, ...
    'ResponseLabels',ResponseLabels, ...
    'ColorBy','t_median', ...
    'FailCountMode','count', ...
    'ShowValues',true, ...
    'ValueFormatT','%.2f', ...
    'ValueFormatPGA','%.3g', ...
    'ValueFormatF','%.0f', ...
    'Colormap','hot', ...
    'RobustLimits',true, ...
    'CLimPctl',[5 95], ...
    'SaveDir',outDir, ...
    'ExportDPI',300, ...
    'FigPosition',[60 60 4200 2800], ...
    'FontName','Arial', ...
    'AxisFontSize',26, ...
    'CellFontSize',12, ...
    'FontWeight','normal', ...
    'TopLabelFontSize',26, ...
    'SideLabelFontSize',26, ...
    'AxesPosition',[0.060 0.055 0.82 0.89], ...
    'TextLuminanceThresh',0.60);

disp('DONE: Detected-transition summary heatmap saved.');
