% ========================================================================
% CALLER: RE-PLOT FROM SAVED COMPARE MODELS METRICS
% ========================================================================
clc; clear; close all;
set(groot,'defaultFigureRenderer','opengl');

baseRoot = 'E:\University\My Thesis\Flac model\New\Maku_PT2_Data';

Models   = {'ELM','ELM-IGWO','ELM-ACOR','ELM-ABC'};
Baseline = 'ELM';

ResponseLabels = {
    '\Delta_x [m]'
    '\Delta_y [m]'
    '\sigma_{xx} [-]'
    '\sigma_{yy} [-]'
    'P_{pore} [-]'
    '\delta\gamma [-]'
    '\delta\nu_s [-]'
};

ResponseMarkers = {'o','s','^','d','p','h','*'};

metricsFile = fullfile(baseRoot, 'COMPARE_models_metrics.xlsx');
% metricsFile = fullfile(baseRoot, 'COMPARE_models_metrics.csv');

if ~exist(metricsFile,'file')
    error('Saved metrics file not found:\n%s', metricsFile);
end

plot_compare_models_metrics_updated( ...
    'OutRoot',     baseRoot, ...
    'SaveDir',     baseRoot, ...
    'MetricsFile', metricsFile, ...
    'WriteExcel',  true, ...
    'Models',      Models, ...
    'Metrics',     {'R2','RMSE','MAE','a10'}, ...
    'Baseline',    Baseline, ...
    'Points',      1:10, ...
    'Responses',   1:7, ...
    'ResponseLabels',  ResponseLabels, ...
    'ResponseMarkers', ResponseMarkers, ...
    'DotBy',       'response', ...
    'ErrorScale',  'normalized', ...
    'NormScope',   'per_response', ...
    'NormMethod',  'p95p5', ...
    'NormRefModel','ELM', ...
    'MinSafe',     50, ...
    'LogFloor',    1e-10, ...
    'RatioFloor',  1e-10, ...
    'DeltaClip',   6, ...
    'MarkerSize',  42, ...
    'MarkerLineWidth', 0.6, ...
    'ShowLegend',  true, ...
    'DashboardLegendGap', true, ...
    'DeltaLegendGap',     true, ...
    'DashboardLegendPosition', [0.395 0.905 0.21 0.055], ...
    'DeltaLegendPosition',     [0.395 0.905 0.21 0.055], ...
    'WinsLegendLocation',      'northeast', ...
    'Padding',     'compact', ...
    'TileSpacing', 'compact', ...
    'FigPosition', [60 60 4200 2800], ...
    'ExportDPI',   300);

disp('DONE');