clc;
clear;
close all;

set(groot,'defaultFigureRenderer','opengl');

MethodTag = 'ELMIGWO';

outRoot = fullfile('E:\University\My Thesis\Flac model\New\Maku_PT2_Data\', ...
    [MethodTag '_FULL70_OUT']);

if ~exist(outRoot,'dir')
    error('Output root not found:\n%s', outRoot);
end

Points = 1:10;
Responses = 1:7;

ResponseLabels = {
    '\Delta_x [m]'
    '\Delta_y [m]'
    '\sigma_{xx} [-]'
    '\sigma_{yy} [-]'
    'P_{pore} [-]'
    '\delta\gamma [-]'
    '\delta\nu_s [-]'
};

pngOut = fullfile(outRoot, ['ALL70_SAFE_obs_vs_pred_' MethodTag '.png']);

FigPosition = [20 20 9000 9000];

plot_grid_obs_vs_pred_7x10_updated(outRoot, ...
    'Points', Points, ...
    'Responses', Responses, ...
    'MethodTag', MethodTag, ...
    'PointTitleYOffset', -0.016, ...
    'ResponseLabels', ResponseLabels, ...
    'FigPosition', FigPosition, ...
    'MarkerSize', 2.5, ...
    'PlotFraction', 0.33, ...
    'RandomSeed', 1, ...
    'TickMode', 'smart', ...
    'MaxTicks', 3, ...
    'TickLength', 0.035, ...
    'GuideMode', 'all', ...
    'GuideFocusPrctLo', 1, ...
    'GuideFocusPrctHi', 99, ...
    'RowLabelX', -0.40, ...
    'ShowGlobalPointLabel', false, ...
    'ShowGlobalResponseLabel', false, ...
    'ShowProgressiveTiles', true, ...
    'LeftMargin', 0.055, ...
    'RightMargin', 0.025, ...
    'BottomMargin', 0.100, ...
    'TopMargin', 0.035, ...
    'HGap', 0.016, ...
    'VGap', 0.036, ...
    'BottomLabelY', 0.045, ...
    'LeftGlobalLabelX', 0.013, ...
    'LabelFontSize', 18, ...
    'HeaderFontSize', 12, ...
    'TileFontSize', 8, ...
    'R2FontSize', 8, ...
    'UseCompactExponentLabels', true, ...
    'ExponentThreshold', 2, ...
    'ExponentYOffsetFrac', 0.035, ...
    'ExponentXOffsetFrac', 0.020, ...
    'ExportDPI', 300, ...
    'SavePNG', pngOut);

fprintf('Saved:\n%s\n', pngOut);