clc; clear; close all;
set(groot,'defaultFigureRenderer','opengl');

FT_file   = 'E:\University\My Thesis\Flac model\New\Maku_PT2_Data\Data\FAILURE_TIMES_v6.mat';
FULL_file = 'E:\University\My Thesis\Flac model\New\Maku_PT2_Data\Data\FULL_ALL_POINTS_ALL_RESPONSES_XY.mat';
outDir    = 'E:\University\My Thesis\Flac model\New\Maku_PT2_Data\Failure plots';

if ~exist(outDir,'dir'), mkdir(outDir); end

plot_pga_cdfs_all70(FT_file, FULL_file, ...
    'FailureMode','response', ...
    'FigMode','all_in_one', ...
    'MinFailed',10, ...
    'SaveDir',outDir, ...
    'ExportDPI',300, ...
    'FigPosition',[60 60 4200 2800], ...
    'FontName','Arial', ...
    'FontSize',18);

disp('DONE: PGA-at-failure CDFs (ALL 70)'); 