clc; clear; close all;

outRoot = 'E:\University\My Thesis\Flac model\New\Maku_PT2_Data\ELMIGWO_FULL70_OUT\';

plot_all70_metric_heatmaps_pretty(outRoot, ...
    'Points', 1:10, ...
    'Responses', 1:7, ...
    'MinSafe', 50, ...
    'A10_Tol', 0.10, ...
    'ClampNonneg', true, ...
    'ShowLabels', true, ...      % <<< show P/R labels
    'FigurePrefix', 'ALL 70 | SAFE metrics (labeled)', ...
    'SaveDir', outRoot, ...
    'ExportDPI', 300, ...
    'MinFigPixels', [1600 1000], ...
    'RobustLimits', true, ...
    'CLimPctl', [2 98]);
