clc; clear; close all;
set(groot,'defaultFigureRenderer','opengl');

full_mat = 'E:\University\My Thesis\Flac model\New\Maku_PT2_Data\Data\FULL_ALL_POINTS_ALL_RESPONSES_XY.mat';
FT_file  = 'E:\University\My Thesis\Flac model\New\Maku_PT2_Data\Data\FAILURE_TIMES_v6.mat';
outDir   = 'E:\University\My Thesis\Flac model\New\Maku_PT2_Data\Failure plots';

if ~exist(outDir,'dir'), mkdir(outDir); end

ResponseLabels = {
    '\Delta_x [m]'
    '\Delta_y [m]'
    '\sigma_{xx} [-]'
    '\sigma_{yy} [-]'
    'P_{pore} [-]'
    '\delta\gamma [-]'
    '\delta\nu_s [-]'
};

plot_grid_median_failure_pga_7x10(full_mat, FT_file, ...
    'FailureMode','response', ...
    'Points',1:10, ...
    'Responses',1:7, ...
    'ResponseLabels',ResponseLabels, ...
    'ShowValues',true, ...
    'ValueFormat','%.3g', ...
    'ShowFailedPct',true, ...
    'PctFormat','%.0f%%', ...
    'TextMode','both', ...
    'Colormap','hot', ...
    'RobustLimits',true, ...
    'CLimPctl',[5 95], ...
    'SaveDir',outDir, ...
    'FileTag','', ...
    'ExportDPI',300, ...
    'FigPosition',[60 60 4200 2800], ...
    'FontName','Arial', ...
    'FontSize',18, ...
    'CellFontSize',14);

disp('DONE: Median failure PGA heatmap saved.');