clc; clear; close all;

outRoot = 'E:\University\My Thesis\Flac model\New\Maku_PT2_Data\ELMIGWO_FULL70_OUT\';

plot_grid_metrics_heatmaps_7x10(outRoot, ...
    'Points',       1:10, ...
    'Responses',    1:7, ...
    'FilePattern',  '*_obs_pred.csv', ...
    'MinSafe',      50, ...
    'A10_Tol',      0.10, ...
    'ClampNonneg',  true, ...
    'FigurePrefix', 'ALL 70 | SAFE metrics', ...
    'ShowValues',   true, ...
    'ValueFormat',  '%.2g', ...
    'Colormap',     'hot', ...
    'RobustLimits', true, ...
    'CLimPctl',     [2 98], ...
    'SaveDir',      outRoot, ...
    'ExportDPI',    300, ...
    'MinFigPixels', [4200 2800]);

disp('DONE: All 4 grid metric heatmaps generated.');
