function labels = final_response_labels()
%FINAL_RESPONSE_LABELS Manuscript-consistent labels for R1--R7.
% Stress and pore-water-pressure outputs are stored in Pa. Incremental
% shear and volumetric strain are dimensionless.
labels = { ...
    '\Delta_x [m]'; ...
    '\Delta_y [m]'; ...
    '\sigma_{xx} [Pa]'; ...
    '\sigma_{yy} [Pa]'; ...
    'P_{\rm pore} [Pa]'; ...
    '\delta\gamma [-]'; ...
    '\delta\nu_s [-]'};
end
