function manifest = generate_all_final_manuscript_plots(handoffFile, outDir)
%GENERATE_ALL_FINAL_MANUSCRIPT_PLOTS Generate every result figure cited in the paper.
% No model is retrained. Aggregate figures are read from the final handoff
% workbook; prediction grids use saved selected checkpoints; transition
% figures use the current canonical Task 2 data files.

root=setup_task2;
if nargin<1||isempty(handoffFile)
    handoffFile=find_project_file(root,'task2_final_manuscript_handoff_*.xlsx');
end
if nargin<2||isempty(outDir)
    outDir=fullfile(root,'results','final_manuscript_figures');
end
assert(isfile(handoffFile),'Final handoff workbook not found: %s',handoffFile);
if ~isfolder(outDir),mkdir(outDir);end
cfg=task2_config(root);
assert(isfile(cfg.failure_file),'Missing current failure database: %s',cfg.failure_file);
assert(isfile(cfg.consolidated_file),'Missing current consolidated dataset: %s',cfg.consolidated_file);
assert(isfile(cfg.split_file),'Missing current realization split: %s',cfg.split_file);
[FT_file,FULL_file]=build_current_plot_adapter(fullfile(outDir,'plot_adapter'));

% 1. Final aggregate, response-specific, and neuron-sweep figures.
generate_final_manuscript_figures(handoffFile,outDir);

% 2. Final selected prediction grids using saved held-out predictions.
selectedDir=fullfile(root,'results','final_selected_models');
if ~isfolder(selectedDir),assemble_final_selected_results(false);end
roots=export_original_plot_inputs(selectedDir);
methods={'ELM','ELMABC','ELMACOR','ELMIGWO'};
displayNames={'ELM','ELM-ABC','ELM-ACOR','ELM-IGWO'};
labels=final_response_labels();
for i=1:numel(methods)
    assert(isfield(roots,methods{i})&&isfolder(roots.(methods{i})), ...
        'Saved prediction inputs are unavailable for %s.',methods{i});
    plot_grid_obs_vs_pred_7x10(roots.(methods{i}), ...
        'Points',1:10,'Responses',1:7,'MethodTag',displayNames{i}, ...
        'ResponseLabels',labels,'PointTitleYOffset',-0.016, ...
        'FigPosition',[20 20 9000 9000],'MarkerSize',2.5, ...
        'PlotFraction',0.33,'RandomSeed',1,'TickMode','smart', ...
        'MaxTicks',3,'TickLength',0.035,'GuideMode','all', ...
        'GuideFocusPrctLo',1,'GuideFocusPrctHi',99,'RowLabelX',-0.40, ...
        'ShowGlobalPointLabel',false,'ShowGlobalResponseLabel',false, ...
        'ShowProgressiveTiles',false,'LeftMargin',0.055,'RightMargin',0.025, ...
        'BottomMargin',0.100,'TopMargin',0.035,'HGap',0.016,'VGap',0.036, ...
        'BottomLabelY',0.045,'LeftGlobalLabelX',0.013,'LabelFontSize',18, ...
        'HeaderFontSize',12,'TileFontSize',8,'R2FontSize',8, ...
        'UseCompactExponentLabels',true,'ExponentThreshold',2, ...
        'ExportDPI',300,'SavePNG',fullfile(outDir, ...
        sprintf('ALL70_SAFE_obs_vs_pred_%s.png',methods{i})));
    close(gcf);
end

% 3. PGA-at-detected-transition CDF grid used in the main text.
plot_pga_cdfs_grid70(FT_file,FULL_file, ...
    'FailureMode','response','Points',1:10,'Responses',1:7, ...
    'MinFailed',10,'ShowMedian',true,'ShowN',true,'UseGlobalXLim',true, ...
    'XLimPctl',[1 99],'XLabel','PGA at detected transition', ...
    'ResponseLabels',labels,'SaveDir',outDir,'ExportDPI',300, ...
    'FigPosition',[60 60 4200 2800],'FontName','Arial', ...
    'FontSize',12,'LabelFontSize',18,'NFontSize',11);
close(gcf);

% 4. Composite median detected-transition summary used in the main text.
plot_grid_failure_summary_7x10(FT_file,FULL_file, ...
    'FailureMode','response','Points',1:10,'Responses',1:7, ...
    'ResponseLabels',labels,'ColorBy','t_median','FailCountMode','count', ...
    'ShowValues',true,'ValueFormatT','%.2f','ValueFormatPGA','%.3g', ...
    'ValueFormatF','%.0f','Colormap','hot','RobustLimits',true, ...
    'CLimPctl',[5 95],'SaveDir',outDir,'ExportDPI',300, ...
    'FigPosition',[60 60 4200 2800],'FontName','Arial', ...
    'AxisFontSize',26,'CellFontSize',12,'FontWeight','normal', ...
    'TopLabelFontSize',26,'SideLabelFontSize',26, ...
    'AxesPosition',[0.060 0.055 0.82 0.89],'TextLuminanceThresh',0.60);
close(gcf);

% 5. Appendix A median detected-transition time and PGA heatmaps.
plot_grid_median_failure_time_7x10(FT_file, ...
    'FailureMode','response','TimeUnit','s','Points',1:10,'Responses',1:7, ...
    'ResponseLabels',labels,'ShowValues',true,'ValueFormat','%.2f', ...
    'ShowFailedPct',true,'PctFormat','%.0f%%','TextMode','both', ...
    'Colormap','hot','RobustLimits',true,'CLimPctl',[5 95], ...
    'SaveDir',outDir,'FileTag','','ExportDPI',300, ...
    'FigPosition',[60 60 4200 2800],'FontName','Arial','FontSize',26, ...
    'CellFontSize',12,'TopLabelFontSize',26,'SideLabelFontSize',26, ...
    'AxesPosition',[0.060 0.055 0.82 0.89]);
close(gcf);

plot_grid_median_failure_pga_7x10(FULL_file,FT_file, ...
    'FailureMode','response','Points',1:10,'Responses',1:7, ...
    'ResponseLabels',labels,'ShowValues',true,'ValueFormat','%.3g', ...
    'ShowFailedPct',true,'PctFormat','%.0f%%','TextMode','both', ...
    'Colormap','hot','RobustLimits',true,'CLimPctl',[5 95], ...
    'SaveDir',outDir,'FileTag','','ExportDPI',300, ...
    'FigPosition',[60 60 4200 2800],'FontName','Arial','FontSize',26, ...
    'CellFontSize',12,'TopLabelFontSize',26,'SideLabelFontSize',26, ...
    'AxesPosition',[0.060 0.055 0.82 0.89]);
close(gcf);

% 6. Appendix A aggregated PGA-at-detected-transition CDF.
plot_pga_cdfs_all70(FT_file,FULL_file, ...
    'FailureMode','response','FigMode','all_in_one','MinFailed',10, ...
    'XLabel','PGA at detected transition','SaveDir',outDir, ...
    'ExportDPI',300,'FigPosition',[60 60 4200 2800], ...
    'FontName','Arial','FontSize',18,'LabelFontSize',22);
close(gcf);

% 7. Retain the additional author-style diagnostics generated by the package.
generate_failure_screening_report;
generate_original_task2_plots(selectedDir,1:10,1:7, ...
    'Silent',true,'CloseFigures',true);

expected={ ...
 'CDF_PGAfail_GRID70_mode_response.png'; ...
 'ALL70_failure_summary_mode_response_color_t_median.png'; ...
 'ALL70_SAFE_obs_vs_pred_ELMIGWO.png';'COMPARE_dashboard.png'; ...
 'COMPARE_wins_top2.png'; ...
 'ALL70_median_failure_time_mode_response_unit_s.png'; ...
 'ALL70_median_failure_PGA_response.png'; ...
 'CDF_PGAfail_ALL70_mode_response.png'; ...
 'ALL70_SAFE_obs_vs_pred_ELM.png'; ...
 'ALL70_SAFE_obs_vs_pred_ELMABC.png'; ...
 'ALL70_SAFE_obs_vs_pred_ELMACOR.png'};
exists=cellfun(@(n)isfile(fullfile(outDir,n)),expected);
manifest=table(string(expected),exists, ...
    'VariableNames',{'manuscript_file','generated'});
writetable(manifest,fullfile(outDir,'final_manuscript_figure_manifest.csv'));
if ~all(exists)
    warning('Task2:IncompleteFigureSet','Some manuscript result figures were not generated.');
end
disp(manifest);
fprintf('All final result figures were written to:\n%s\n',outDir);
end

function path=find_project_file(root,pattern)
% Search the Task 2 package and nearby project Data/results folders.
% The user's normal layout places Data beside Revision_codes.
bases={root}; current=root;
for i=1:4
    current=fileparts(current);
    if isempty(current),break;end
    bases{end+1}=current; %#ok<AGROW>
end
candidates={};
for i=1:numel(bases)
    candidates=[candidates, {bases{i},fullfile(bases{i},'data'), ...
        fullfile(bases{i},'Data'),fullfile(bases{i},'results')}]; %#ok<AGROW>
end
path=''; newest=-inf;
for i=1:numel(candidates)
    if ~isfolder(candidates{i}),continue;end
    d=dir(fullfile(candidates{i},'**',pattern));
    if isempty(d),continue;end
    [stamp,k]=max([d.datenum]);
    if stamp>newest
        newest=stamp; path=fullfile(d(k).folder,d(k).name);
    end
end
if isempty(path)
    warning('Task2:ProjectFileNotFound', ...
        'Could not locate %s below the Task 2 package or nearby Data/results folders.',pattern);
else
    fprintf('Using %s\n  %s\n',pattern,path);
end
end
